config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get '/home', to: 'pages#home'
	resources :recipes do 
		member do 
			post 'like'
		end
		resources :comments, module: :recipes 
	end

	resources :chefs, except: [:new, :destroy] do 
		resources :comments, module: :chefs
	end

	get '/register', to: 'chefs#new'

	get '/login', to: 'logins#new'
	post '/login', to: 'logins#create'
	get '/logout', to: 'logins#destroy'

	resources :styles, only: [:new, :create, :show]
	resources :ingredients, only: [:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ActiveRecord::Base
	has_many :recipes
	has_many :likes
	has_many :comments, as: :commentable
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { minimum: 3, maximum: 40}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105}, 
									  uniqueness: { case_sensitive: false }, 
									  format: { with: VALID_EMAIL_REGEX}
	has_secure_password
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	validates :name, presence: true,  length: { minimum: 2, maximum: 25 }
	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :chef
	belongs_to :recipe

	validates_uniqueness_of :chef, scope: :recipe 
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :chef
	has_many :likes, dependent: :destroy
	has_many :recipe_styles, dependent: :destroy
	has_many :styles, through: :recipe_styles
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients
	has_many :comments, as: :commentable
	validates :chef_id, presence: true
	validates :name, presence: true, length: { minimum: 5, maximum: 100}
	validates :summary, presence: true, length: { minimum: 10, maximum: 150}
	validates :description, presence: true, length: { minimum: 20, maximum: 500}
	mount_uploader :picture, PictureUploader
	validate :picture_size
	default_scope -> { order(updated_at: :desc) }

	def thumbs_up_total
		self.likes.where(like: true).size
	end

	def thumbs_down_total
		self.likes.where(like: false).size
	end

	private
		def picture_size
			if picture.size > 5.megabytes
				errors.add(:picture, "should be less than 5MB")
			end
		end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :ingredient
end

app/models/recipe_style.rb
class RecipeStyle < ActiveRecord::Base
	belongs_to :recipe
	belongs_to :style
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :recipe
	belongs_to :chef
	validates :chef_id, presence: true
	validates :recipe_id, presence: true
	validates :body, presence: true, length: { minimum: 5, maximum: 500}
end

app/models/style.rb
class Style < ActiveRecord::Base
	validates :name, presence: true,  length: { minimum: 2, maximum: 25 }
	has_many :recipe_styles 
	has_many :recipes, through: :recipe_styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to recipes_path
  	end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

	before_action :set_chef, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update]

	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 2)
	end

	def new
		@chef = Chef.new
	end

	def create
		@chef = Chef.new(chef_params)
		if @chef.save
			flash[:success] = "Your account was created successfully"
			session[:chef_id] = @chef.id
			redirect_to recipes_path
		else
			render 'new'
		end
	end


	def edit		
	end

	def update
		
		if @chef.update(chef_params)
			flash[:success] = "Your profile has been updated successfully"
			redirect_to chef_path(@chef)
		# TODO change to show chef page
		else
			render 'edit'
		end
	end

	def show
		@recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
	end

	private

		def chef_params
			params.require(:chef).permit(:name, :email, :password)
		end

		def set_chef
			@chef = Chef.find(params[:id])
		end

		def require_same_user
			if current_user != @chef
				flash[:danger] = "You can only edit your own profile"
				redirect_to root_path
			end
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_user

	def create
		@comment = @commentable.comments.new comment_params
		@comment.chef_id = current_user
		@comment.save
		redirect_to @commentable, notice: "Thanks for the contribution!"
	end

	private

		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def new
	end

	def create
		chef = Chef.find_by(email: params[:email])
		if chef && chef.authenticate(params[:password])
			session[:chef_id] = chef.id
			flash[:success] = "You are logged in"
			redirect_to recipes_path
		else
			flash.now[:danger] = "Your email address or password does not match"
			render 'new'
		end
	end

	def destroy
		session[:chef_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :set_recipe, only: [:edit, :update, :show, :like]
	before_action :require_user, except: [:show, :index, :like]
	before_action :require_user_like, only: [:like]
	before_action :require_same_user, only: [:edit, :update]
	before_action :admin_user, only: :destroy

	def index
		@recipes = Recipe.paginate(page: params[:page], per_page: 3)
	end
	

	def show
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		@recipe.chef = current_user

		if @recipe.save
			flash[:success] = "Your recipe was created succesfully!"
			redirect_to recipes_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			flash[:success] = "Your recipe was edited succesfully"
			redirect_to recipe_path(@recipe)
		else
			render :edit
		end
	end

	def like
		like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
		if like.valid?
		flash[:success] = "Your selection was sucessful"
		redirect_to :back
		else
			flash[:danger] = "You can only like/dislike a recipe once"
			redirect_to :back
		end
	end

	def destroy
		Recipe.find(params[:id]).destroy
		flash[:success] = "Recipe Deleted"
		redirect_to recipes_path
	end

	private
		def recipe_params
			params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
		end

		def set_recipe
			@recipe = Recipe.find(params[:id])
		end

		def require_same_user
			if current_user != @recipe.chef and !current_user.admin?
				flash[:danger] = "You can only edit your own recipes"
				redirect_to root_path
			end
		end

		  def require_user_like
  			if !logged_in?
  				flash[:danger] = "You must be logged in to perform that action"
  				redirect_to :back
  			end
  		end	

  		def admin_user
  			redirect_to recipes_path unless current_user.admin?
  		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

	before_action :require_user, except: [:show]

	def new
		@style = Style.new
	end

	def create
		@style = Style.new(style_params)
		if @style.save
			flash[:success] = "Style was created successfully"
			redirect_to recipes_path
		else
			render 'new'
		end
	end


	def style_params
		params.require(:style).permit(:name)
	end

	def show
		@style = Style.find(params[:id])
		@recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(chef, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
		size = options[:size]
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: chef.name, class: "gravatar")
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    	<p> &copy; MyRecipes 2017</p>
    </div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %>"><%= message %>
		<a class="close" data-dismiss="alert">&#215;</a>
		</div>		
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  	<div class="container">
  		<%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
  		<ul class="nav_ul_item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Styles <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Style.all.each do | style | %>
            <li><%= link_to style.name, style_path(style) %></li>
          <% end %>
          <% if logged_in? %>
          <li class="divider"></li>
          <li>
            <%= link_to(new_style_path) do %>
            New Style
            <% end %>
          </li>
          <% end %>
          </ul>
        </li>        
  		</ul>


  	 <ul class="nav_ul_item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          Ingredients <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <% Ingredient.all.each do | ingredient | %>
            <li><%= link_to ingredient.name, ingredient_path(ingredient) %> </li>
          <% end %>
          <% if logged_in? %>
          <li class="divider"></li>
          <li>
            <%= link_to(new_ingredient_path) do %>
            New Ingredient
            <% end %>
          </li>
          <% end %>
          </ul>
        </li>        
      </ul>

      <% if logged_in? %>
  		<div class="nav_item">
  			<%= link_to "New Recipe", new_recipe_path, class: "btn btn-default btn-warning" %>
      </div>
      <ul class="nav_item">
        <li class="dropdown">
          <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
          <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "View Profile", chef_path(current_user) %> </li>
            <li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", logout_path %></li> 
          </ul>
        </li>
      </ul>
      <% else %>
        <div class="nav_item">
          <%= link_to "Log in", login_path, class: "btn btn-default btn-success" %>
        </div>
      <% end %>

  
 	</div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
 <%= render 'layouts/navigation' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to MyRecipes App</h1>

	<h2>This is a test, I don't know what the hell I'm doing :) </h2>

	<%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>

</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="midrow">
			View Recipes as Guest User
		</h3>
		<h2 class="left"> Browse and view recipes as a guest and Sign up!</h2>
		<p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small" %></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midrow">
			Sign in to your account
		</h3>
		<h2 class="left"> Add or update your recipes / Create reviews / Like-dislike recipes and much more!</h2>
		<p><%= link_to "Log in to your account", login_path, class: "btn btn-warning btn-small" %></p>
	</div>

	<div class="col-lg-4">
		<h3 class="midrow">
			View Recipes as Guest User
		</h3>
		<h2 class="left"> Browse and view recipes as a guest and Sign up!</h2>
		<p><%= link_to "Browse Recipe Listings", "", class: "btn btn-warning btn-small" %></p>
	</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="alert alert-danger col-md-8 col-md-offset-2">
		<h5>Please correct the following errors:</h5>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
	<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
	<h1><%= title %></h1>
	<hr>
</p>